export const OpeningHoursIdentifier = [
    "horario",
    "horarios",
    "abre",
    "cierra",
    "hora",
    "horas",
    "día",
    "días",
    "semana",
    "semanas",
    "mes",
    "meses",
    "año",
    "años",
    "abierto",
    "cerrado",
    "cuándo",
    "cuando abre",
    "cuando cierra",
    "cuando atiende",
    "atiende",
    "atención",
    "atender",
    "atencion",
    "horario de atención",
    "horario de atencion",
]