

export const SaludarIdentifier = [
    "saludar",
    "saludos",
    "hola",
    "buenos días",
    "buenas tardes",
    "buenas noches",
    "buen día",
    "buenas tardes",
    "buenas noches",
    "qué tal",
    "qué onda",
    "qué hubo",
    "qué pasa",
    "qué hay",
    "qué hay de nuevo",
    "qué hay de nuevo viejo",
    "qué hay de nuevo vieja",
    "cómo estás",
    "cómo está",
    "cómo estás tú",
    "cómo está usted",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "cómo estás vos",
    "buen día"
]